### ISSUE TITLE
Clear form data doesn't work when HTML render is selected

### ISSUE THREAD

**Issue by zzap** [IONOS-WordPress/cfhack2024-wp-react-jsonschema-form#8]
Regardless of in which render the field is populated, when HTML is selected the form data can not be cleared. It can be cleared only from Gutenberg renderer.

EDIT: This appears to be inconsistent and occurs only in specific situations (unknown at the moment).

https://github.com/lgersman/cfhack2024-wp-react-jsonschema-form/assets/1508963/f60b50b3-887d-4f88-82a8-ad1e4d8443c8

**Comment by genesfa** [comment]
The Problem is that the "Clear from data" button only clears the form data not more this needs to be changed.
We sadly didn't have the time at the Hackathon for it.

Info:
Look in playground.js for setFormData({})

**Comment by lgersman** [comment]
Done
