### ISSUE TITLE
Gutenberg date and time widgets return date-time value

### ISSUE THREAD

**Issue by zzap** [IONOS-WordPress/cfhack2024-wp-react-jsonschema-form#9]
HTML render returns only date when `date` format is defined and only time when format is `time`. Gutenber returns `date-time` format for both `date` and `time`.

https://github.com/lgersman/cfhack2024-wp-react-jsonschema-form/assets/1508963/6708d073-1c15-4f65-a9b1-0d1f6ff6e210

**Comment by Bl4d3s** [comment]
Note: The Gutenberg TimePicker shows always a date picker as well (see [#52734](https://github.com/WordPress/gutenberg/issues/52734)), its hidden via CSS for now
